version: '3.9'

services:
    app:
        build: .
        command: npm start
        ports: 
            - '3000:3000'
        volumes:
            - .:/usr/app
        depends_on: 
            - db
        links:
            - db

    db:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - /my/own/datadir:/data/db